# Generated by Django 4.0.5 on 2022-06-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('is_starchaser2017', 'Is StarChaser2017 Member')]},
        ),
        migrations.RemoveField(
            model_name='report',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
